config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :subjects
  resources :posts
  devise_for :users

  root 'landing#index'
  get '/my_page' => 'my_page#index'
  get '/users/edit' => 'devise/registrations#edit'

  get '/posts/:post_id/subjects/new' => 'subjects#new'
  get '/topten' => 'toptens#index'

  post '/posts/:post_id/like' => 'posts#like_toggle'
  get '/vote', to: 'posts#vote', as: 'vote'
  
  # devise_scope :user do
  #   get '/login' => 'devise/sessions#new'
  #   post '/login' => 'devise/session#create'
  #   delete '/sign_out' => 'devise/session#destroy'
  #   get '/sign_up' => 'devise/registrations#new'
  #   post 'users' => 'devise/registrations#create'
  #   get '/edit' => 'devise/registrations#edit'
  #   patch '/update' => 'devise/registrations#update'
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
    belongs_to :parent, class_name: 'Comment', optional: true
    has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index ]
  around_action :raise_action_on_unpermitted_parameters, only: %i[create update]

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_back fallback_location: :root, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: :root, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id, :comment_id)
    end

    def raise_action_on_unpermitted_parameters
      original = ActionController::Parameters.action_on_unpermitted_parameters
      ActionController::Parameters.action_on_unpermitted_parameters = :raise
      yield
    ensure
      ActionController::Parameters.action_on_unpermitted_parameters = original
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :content %>
  </div>

  <%= form.hidden_field :post_id, :value => params[:id] %>
  <%= form.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= form.submit "등록" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment, post_id: @post_id %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<div class="comment_index">
  <% if(comments) %>
    <% comments.each do |comment| %>
      <% 
        user_id = comment.user_id
        comm_user = User.find(user_id)
      %>
      <strong><%= comm_user.nickname %></strong><br>
      <%= comment.content %>
      <% if(comment.user_id == current_user.id) %>
        <div class="crud">
          <%= link_to '수정', edit_comment_path(comment) %>
          <%# javascript 사용해서 버튼 누르면 수정 폼 나오게
          <script>
            수정 button action
          </script> 
          %>
          <%= link_to '삭제', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
      <hr>
    <% end %>
  <% else %>
    댓글이 없습니다! 첫 댓글을 남겨보세요!
  <% end %>
  <%= render 'comments/form', comment: Comment.new %>
</div>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>