config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :subjects
  resources :posts
  devise_for :users

  root 'landing#index'
  get '/my_page' => 'my_page#index'
  get '/users/edit' => 'devise/registrations#edit'

  get '/posts/:post_id/subjects/new' => 'subjects#new'
  get '/topten' => 'toptens#index'

  post '/posts/:post_id/like' => 'posts#like_toggle'
  get '/vote', to: 'posts#vote', as: 'vote'
  
  # devise_scope :user do
  #   get '/login' => 'devise/sessions#new'
  #   post '/login' => 'devise/session#create'
  #   delete '/sign_out' => 'devise/session#destroy'
  #   get '/sign_up' => 'devise/registrations#new'
  #   post 'users' => 'devise/registrations#create'
  #   get '/edit' => 'devise/registrations#edit'
  #   patch '/update' => 'devise/registrations#update'
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :post, :optional => true
    has_many :subjects_users, dependent: :destroy
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index ]
  # before_action :correct_user, only: %i[ edit update destroy ]

  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1 or /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new(post_id: params[:post_id])
    @subjects = Subject.where(post_id: params[:post_id])

    # @post = Post.find(params[:post_id])
    # @post.subjects.new
    # @subjects = @post.subjects
  end

  # GET /subjects/1/edit
  def edit
    @post_id = params[:post_id]
  end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to "/posts/#{@subject.post_id}/subjects/new", notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to "/posts/#{@subject.post_id}/subjects/new", notice: "Subject was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "Subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:sub_con, :votes, :post_id)
    end

    # user authenticate
    # def correct_user
    #   @subject = current_user.subjects.find_by(id: params[:id])
    #   redirect_to posts_path, notice: "접근 권한이 없습니다." if @subject.nil?
    # end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field d-none">
    <%= form.label :post_id %>
    <%= form.number_field :post_id, type: :hidden %>
  </div>

  <div class="subject_con">
    <div class="field d-inline">
      <%= form.label :sub_cons %>
      <%= form.text_field :sub_con, :required => true, placeholder: '항목을 입력하세요', class: 'subject_input' %>
    </div>

    <div class="actions d-inline">
      <%= form.submit "#{message}", class: 'create_btn' %>
    </div>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Sub con</th>
      <th>Votes</th>
      <th>postid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.sub_con %></td>
        <td><%= subject.votes %></td>
        <td><%= subject.post_id %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

      <%= subject.inspect %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<div class="new container">
    <h1>Step 2</h1>
    <!-- message 말고 subject id 여부에 따라 수정 생성 버튼 나누기 -->

    <% @subjects.each do |subject| %>
        <%= render 'form', subject: subject, message: '수정' %>
    <% end %>

    <%= render 'form', subject: @subject, message: '생성' %>

    <%= link_to '완료', "/posts/#{@post_id}", class: 'submit_btn' %>
</div>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sub con:</strong>
  <%= @subject.sub_con %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @subject.votes %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>